# Generated by Django 5.0 on 2024-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banaoapp', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='valpass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='valpass',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
