# Generated by Django 5.0 on 2024-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banaoapp', '0003_doctor_valpass_patient_valpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='valpass',
            new_name='confirmpass',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='valpass',
            new_name='confirmpass',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
