# Generated by Django 5.0 on 2024-03-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banaoapp', '0004_rename_valpass_doctor_confirmpass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='confirmpass',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='confirmpass',
        ),
    ]
